### ISSUE TITLE
Precompiled Binaries

### ISSUE THREAD

**Issue by Portalboy** [Elveskevtar/SmartMoving#1]
Is there any chance precompiled jar binaries could be added to as Releases? That would make it much more convenient to try out. I think for most players if they're unsure if a rewrite is going to be stable, they won't want to go through the effort of figuring out how to build it if there's a decent chance it won't work.

**Comment by DoomRater** [comment]
I can rapidly test things and offer bug reports with a precompiled jar.  I've been meaning to create a dev environment for ages but simply never got around to it.

Edit: can't speak for those who are compiling as I've never set up an environment to even try.

**Comment by ScienceDrummer** [comment]
Are you guys having problems compiling SmartRender by any chance?

**Comment by elveskevtar** [comment]
Hey everyone, sorry. I guess it has taken quarantine to make me inspired to work on such a frustrating piece of legacy code that this mod is. Regardless, I have published a release. Feel free to test and I will be actively working on it. There are quite a few bugs but it is finally a point where I feel comfortable to release for 1.12.2 without feeling like a failure myself.

I think I am going to keep working on fixing and improving it for 1.12.2 until I feel like the code is actually maintainable (it is not at the moment). Then I will continue working on 1.13+
