### ISSUE TITLE
Game crashes with the RC3 build when you try to use third person

### ISSUE THREAD

**Issue by TracynSenar** [Elveskevtar/SmartMoving#4]
Here are the crash logs
[crash-2019-10-29_02.17.53-client.txt](https://github.com/Elveskevtar/SmartMoving/files/3781236/crash-2019-10-29_02.17.53-client.txt)
[crash-2019-10-29_02.22.43-client.txt](https://github.com/Elveskevtar/SmartMoving/files/3781237/crash-2019-10-29_02.22.43-client.txt)
I suppose it's a problem with one of the render APIs
Tried it on a completely clean game, so it's definitely not a compatibility issue
Is there any way to fix this?

**Comment by elveskevtar** [comment]
Yeah, I actually fixed this. It was an issue with the API core mods and I'm not entirely sure how to fix it for future releases (I have an idea I will have to test out) but you can check the new release. It includes all of the core mods and Smart Render jars.
