### ISSUE TITLE
Biomes'o'Plenty crash

### ISSUE THREAD

**Issue by jtljac** [Elveskevtar/SmartMoving#9]
[crash-2020-04-11_14.36.17-client.txt](https://github.com/Elveskevtar/SmartMoving/files/4464682/crash-2020-04-11_14.36.17-client.txt)
While climbing a Biomes'o'Plenty tree, the game crashed with this error:
`java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=biomesoplenty:willow_vine, properties=[east, north, south, up, west]}`

**Comment by elveskevtar** [comment]
It looks like a simple fix but it's likely going to be a low priority until I finish the major bugs with the mod. Then I'll tackle some of this external mod support. Or someone else could try their hand at it and submit a PR! Thank you.

**Comment by elveskevtar** [comment]
Thanks for the PR!
